#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Create log folder
if [ ! -d /config/logs ];then
    mkdir /config/logs/
fi

# Fix folder permissions
chown -R abc:abc /app
chown -R abc:abc /default
chown -R abc:abc /config