#!/usr/bin/with-contenv bash
# shellcheck shell=bash

REPO_PATH="/config/repo"

if ! grep -q "$REPO_NAME" "/etc/pacman.conf"; then
    echo -e "[$REPO_NAME]\nSigLevel = Optional TrustAll\nServer = file://${REPO_PATH}" >> /etc/pacman.conf	
fi

# Create repo and chown it
if [ -d $REPO_PATH ];then #Check if repo already exists
    chown abc:abc $REPO_PATH
    if [ ! -f "${REPO_PATH}/${REPO_NAME}".db.tar.xz ];then
        runuser -l abc -c "repo-add ${REPO_PATH}/${REPO_NAME}.db.tar.xz &> /dev/null"
        echo -e "\e[32mSucessfully created the repo: ${REPO_NAME}\e[39m"
    fi
else
    mkdir $REPO_PATH
    chown abc:abc $REPO_PATH
    runuser -l abc -c "repo-add ${REPO_PATH}/${REPO_NAME}.db.tar.xz &> /dev/null"
    tar -xf /default/nginx.tar.gz -C $REPO_PATH
    echo -e "\e[32mSucessfully created the repo: ${REPO_NAME}\e[39m"
fi

# Update the System
pacman -Syu --noconfirm &> /dev/null

# Create aliases
if [ ! -f /usr/bin/rm ];then
    echo -e '#!/bin/bash\nrunuser -l abc -c "/app/remove.sh $*"' > /usr/bin/rm
    chmod +x /usr/bin/rm
fi

# Add Cronjob
echo "${CRON} ./app/update.sh >> /config/logs/update" > /var/spool/cron/abc