#!/usr/bin/with-contenv bash
# shellcheck shell=bash

REPO_PATH="/config/repo"

success_notification ()
{
	response='
	{
	  "embeds":[
	    {
	      "description":":white_check_mark: The package has been added sucessfully to the repo.",
	      "color": 7844437,
	      "footer":{
	        "text":"Powered by MiguelNdeCarvalho"
	      },
	      "author":{
	        "name":"'$REPO_NAME' bot",
	        "icon_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Archlinux-icon-crystal-64.svg/1024px-Archlinux-icon-crystal-64.svg.png"
	      },
	      "fields":[
	        {
	          "name":"Package:",
	          "value":"`'$1'`"
	        }
	      ]
	    }
	  ],
	  "username":"'$REPO_NAME' bot",
	  "avatar_url":"https://img.icons8.com/ultraviolet/240/000000/bot.png"
	}'

	curl -fsSL -H "Content-Type: application/json" -d "${response}" "${DISCORD_WEBHOOK}"
}

fail_notification ()
{
	response='
	{
	  "embeds":[
	    {
	      "description":":x: The package couldn`t be added to the repo.",
	      "color": 14495300,
	      "footer":{
	        "text":"Powered by MiguelNdeCarvalho"
	      },
	      "author":{
	        "name":"'$REPO_NAME' bot",
	        "icon_url":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Archlinux-icon-crystal-64.svg/1024px-Archlinux-icon-crystal-64.svg.png"
	      },
	      "fields":[
	        {
	          "name":"Package:",
	          "value":"`'$1'`"
	        },
	        {
	          "name":"Logs:",
	          "value":"[Click here]('$2')"
	        }
	      ]
	    }
	  ],
	  "username":"'$REPO_NAME' bot",
	  "avatar_url":"https://img.icons8.com/ultraviolet/240/000000/bot.png"
	}'
	
	curl -fsSL -H "Content-Type: application/json" -d "${response}" "${DISCORD_WEBHOOK}"
}

package_exists ()
{
	for f in "$REPO_PATH/$1"*; do
		if [ -e "$f" ];then 
			return 0
		else
			return 1
		fi
		break
	done
}

build ()
{
	echo -e "\e[34mAdding ${1} to the repo!\e[39m"
	BUILD_START=$(date +%s)
	runuser -l abc -c "aur sync --no-view --noconfirm \
		-d ${REPO_NAME} \
		-r ${REPO_PATH} \
		${1} &> /dev/null"
	if ! runuser -l abc -c "aur sync --no-view --noconfirm -d ${REPO_NAME} -r ${REPO_PATH} ${1} &> /dev/null";then
		echo -e "\e[31mSomething went wrong during the build of ${1}!\e[39m"
		send_notification "Build failed for $1"
	else
		BUILD_END=$(date +%s)
		DIFF=$((BUILD_END - BUILD_START))
		echo -e "\e[32mSucessfully built ${1} in $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds.\e[39m"
	fi
}

for package in $(echo "$PACKAGES" | tr "," " "); do
    if package_exists "$package";then
        echo -e "\e[33m${package} is already on the repo!\e[39m"
    else
        build "$package"
    fi
done