name: Test Code

on:
  pull_request:
    branches:
      - main

jobs:
  lint-bash:
    name: Lint Bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Bash (Shellcheck)
        uses: ludeeus/action-shellcheck@master
  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Dockerfile (Hadolint)
        uses: hadolint/hadolint-action@v2.1.0
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          file: ./Dockerfile
          tags: |
            miguelndecarvalho/docker-miguelndecarvalho-repo:latest
            ghcr.io/miguelndecarvalho/docker-miguelndecarvalho-repo:latest